apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-argocd
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80


apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: nginx
    app.kubernetes.io/instance: argocd-test-application
  name: nginx-argocd-svc
  namespace: argocd-applications
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx
  type: NodePort
status:
  loadBalancer: {}


kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: argocd-nginx-pod
  name: argocd-nginx-pod
spec:
  containers:
  - image: nginx
    name: argocd-nginx-pod
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}


